{   'active': False,
    'application': False,
    'author': 'Marc Wimmer (marc@itewimmer.de)',
    'category': 'uncategorized',
    'css': [],
    'data': [   'cronjobs/run.xml',
                'views/cronjob_group.xml',
                'views/form.xml',
                'views/search.xml',
                'views/tree.xml',
                'views/menu.xml',
                'security/ir.model.access.csv'],
    'demo': [],
    'demo_xml': [],
    'depends': ['base', 'mail', 'method_trigger'],
    'description': '',
    'installable': True,
    'js': [],
    'name': 'datapolice',
    'qweb': [],
    'test': [],
    'version': '14.0.1.3',
    'web': False}
